resources:
  apps:
    hello-world-app:
      name: hello-world-app
      description: "A Hello World Next.js App"
      # The source code path is relative to this file (resources/app.yml)
      # Since package.json is in the project root, we point to the parent directory.
      source_code_path: ../
      command: ["npm", "run", "start"]
      env:
        NODE_ENV: production

